### ISSUE TITLE
Why not use crate iffc for parsing blorb files?

### ISSUE THREAD

**Issue by grumble1965** [UncleScientist/caskly#1]
I found your videos on this project this week, and I'm wondering why you didn't start with the iffc crate to parse blorb files?
https://docs.rs/iffc/latest/iffc/

I'm an utter Rust newbie, but I think iffc::Decoder would parse the blorb files for you, returning a list of struct Chunk, which would then be specialized for each of the chunk types defined in the blorb spec?  Maybe it's just more fun to roll your own? :)

Love your work, and I miss seeing your videos on YouTube, but I see you're mostly on Twitch now.  You motivated me to rewrite my python Advent of Code solutions using unit tests and an AoC solution runner. 

Cheers,
Kelly

**Comment by UncleScientist** [comment]
Thanks for pointing out that crate! I took a look at it and, from what I can tell, it would replace the get_next_chunk() function, so like you say, it's simple enough to roll my own.

Also, it appears that it doesn't handle the "round up" requirement, if I'm reading the code correctly. The Blorb standard says that, if a chunk is an odd number of bytes, there is one byte of padding after it to ensure that the next chunk starts on an even byte boundary.

Finally, while the source is open, the development doesn't appear to be. By that I mean there's no gitlab/github/sourceforge/etc site that I can find that I can contribute updates to.
